/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockV3Aggregator, MockV3AggregatorInterface } from "../../test/MockV3Aggregator.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "decimals_",
        "type": "uint8"
      },
      {
        "internalType": "int256",
        "name": "initialAnswer",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "description",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint80",
        "name": "roundId_",
        "type": "uint80"
      }
    ],
    "name": "getRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newAnswer",
        "type": "int256"
      }
    ],
    "name": "updateAnswer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "version",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060405161031b38038061031b833981016040819052602b91605f565b5f805460ff191660ff93909316929092179091556001908155600280546001600160501b031916909117905542600355608e565b5f5f60408385031215606f575f5ffd5b825160ff81168114607e575f5ffd5b6020939093015192949293505050565b6102808061009b5f395ff3fe608060405234801561000f575f5ffd5b5060043610610060575f3560e01c8063313ce5671461006457806354fd4d501461007d5780637284e4161461008c5780639a6fc8f5146100cb578063a87a20ce1461011e578063feaf968c14610133575b5f5ffd5b5f5460405160ff90911681526020015b60405180910390f35b60405160018152602001610074565b604080518082018252601781527f4d6f636b204554482f555344205072696365204665656400000000000000000060208201529051610074919061019b565b6100ea6100d93660046101d0565b600154600354919290919081908490565b604080516001600160501b03968716815260208101959095528401929092526060830152909116608082015260a001610074565b61013161012c3660046101fd565b61014f565b005b6002546001546003546001600160501b039092169180836100ea565b6001819055600280546001600160501b0316905f61016c83610214565b91906101000a8154816001600160501b0302191690836001600160501b03160217905550504260038190555050565b602081525f82518060208401528060208501604085015e5f604082850101526040601f19601f83011684010191505092915050565b5f602082840312156101e0575f5ffd5b81356001600160501b03811681146101f6575f5ffd5b9392505050565b5f6020828403121561020d575f5ffd5b5035919050565b5f6001600160501b0382166001600160501b03810361024157634e487b7160e01b5f52601160045260245ffd5b6001019291505056fea26469706673582212202af2f63fe26a15aa29b9ab74a0fd7be537781678729dc7a38dd4fb3c217f890b64736f6c634300081c0033";

  
      type MockV3AggregatorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockV3AggregatorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockV3Aggregator__factory extends ContractFactory {
    
      constructor(...args: MockV3AggregatorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(decimals_: BigNumberish, initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(decimals_, initialAnswer, overrides || {});
    };
    override deploy(decimals_: BigNumberish, initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(decimals_, initialAnswer, overrides || {}) as Promise<MockV3Aggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockV3Aggregator__factory {
      return super.connect(runner) as MockV3Aggregator__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockV3AggregatorInterface {
      return new Interface(_abi) as MockV3AggregatorInterface;
    }
    
    override attach(address: string | Addressable): MockV3Aggregator {
      return super.attach(address) as MockV3Aggregator;
    }
  static connect(address: string, runner?: ContractRunner | null): MockV3Aggregator {
      return new Contract(address, _abi, runner) as unknown as MockV3Aggregator;
    }
  }

  
  