/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AuctionV2Interface extends Interface {
    getFunction(nameOrSignature: "accumulatedFees" | "auctionItems" | "calculateFee" | "calculateFeeRate" | "cancelAuctionItem" | "convertEthToUsd" | "createAuctionItem" | "endAuction" | "getChainlinkDataFeedLatestAnswer" | "getLatestPrice" | "initialize" | "initializeV2" | "owner" | "pause" | "paused" | "pendingReturns" | "placeBid" | "transferOwnership" | "unpause" | "withdrawFees" | "withdrawPendingReturn"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CancelAuction" | "CreateAuction" | "EndAuction" | "FeeCollected" | "FeesWithdrawn" | "Initialized" | "Paused" | "PlaceBid" | "Unpaused" | "WithdrawPendingReturn"): EventFragment;

    encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctionItems', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateFeeRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelAuctionItem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'convertEthToUsd', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuctionItem', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getChainlinkDataFeedLatestAnswer', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLatestPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initializeV2', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingReturns', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawPendingReturn', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctionItems', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateFeeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAuctionItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertEthToUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuctionItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChainlinkDataFeedLatestAnswer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeV2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingReturns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPendingReturn', data: BytesLike): Result;
  }

  
    export namespace CancelAuctionEvent {
      export type InputTuple = [auctionId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [auctionId: bigint, seller: string];
      export interface OutputObject {auctionId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreateAuctionEvent {
      export type InputTuple = [auctionId: BigNumberish, seller: AddressLike, tokenContract: AddressLike, tokenId: BigNumberish, startingBid: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [auctionId: bigint, seller: string, tokenContract: string, tokenId: bigint, startingBid: bigint, endTime: bigint];
      export interface OutputObject {auctionId: bigint, seller: string, tokenContract: string, tokenId: bigint, startingBid: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EndAuctionEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeCollectedEvent {
      export type InputTuple = [auctionId: BigNumberish, feeAmount: BigNumberish, feeRate: BigNumberish];
      export type OutputTuple = [auctionId: bigint, feeAmount: bigint, feeRate: bigint];
      export interface OutputObject {auctionId: bigint, feeAmount: bigint, feeRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlaceBidEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawPendingReturnEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AuctionV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): AuctionV2;
    waitForDeployment(): Promise<this>;

    interface: AuctionV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctionItems: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, string, bigint, bigint, boolean] & {seller: string, tokenContract: string, tokenId: bigint, startingBid: bigint, highestBid: bigint, highestBidder: string, startTime: bigint, endTime: bigint, active: boolean }],
      'view'
    >
    

    
    calculateFee: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calculateFeeRate: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancelAuctionItem: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    convertEthToUsd: TypedContractMethod<
      [ethAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createAuctionItem: TypedContractMethod<
      [tokenContract: AddressLike, tokenId: BigNumberish, startingBid: BigNumberish, endTime: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getChainlinkDataFeedLatestAnswer: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getLatestPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [priceFeed: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initializeV2: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingReturns: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    placeBid: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawPendingReturn: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctionItems'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, string, bigint, bigint, boolean] & {seller: string, tokenContract: string, tokenId: bigint, startingBid: bigint, highestBid: bigint, highestBidder: string, startTime: bigint, endTime: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'calculateFee'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateFeeRate'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAuctionItem'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'convertEthToUsd'): TypedContractMethod<
      [ethAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createAuctionItem'): TypedContractMethod<
      [tokenContract: AddressLike, tokenId: BigNumberish, startingBid: BigNumberish, endTime: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getChainlinkDataFeedLatestAnswer'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLatestPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [priceFeed: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeV2'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingReturns'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawPendingReturn'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CancelAuction'): TypedContractEvent<CancelAuctionEvent.InputTuple, CancelAuctionEvent.OutputTuple, CancelAuctionEvent.OutputObject>;
getEvent(key: 'CreateAuction'): TypedContractEvent<CreateAuctionEvent.InputTuple, CreateAuctionEvent.OutputTuple, CreateAuctionEvent.OutputObject>;
getEvent(key: 'EndAuction'): TypedContractEvent<EndAuctionEvent.InputTuple, EndAuctionEvent.OutputTuple, EndAuctionEvent.OutputObject>;
getEvent(key: 'FeeCollected'): TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PlaceBid'): TypedContractEvent<PlaceBidEvent.InputTuple, PlaceBidEvent.OutputTuple, PlaceBidEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'WithdrawPendingReturn'): TypedContractEvent<WithdrawPendingReturnEvent.InputTuple, WithdrawPendingReturnEvent.OutputTuple, WithdrawPendingReturnEvent.OutputObject>;

    filters: {
      
      'CancelAuction(uint256,address)': TypedContractEvent<CancelAuctionEvent.InputTuple, CancelAuctionEvent.OutputTuple, CancelAuctionEvent.OutputObject>;
      CancelAuction: TypedContractEvent<CancelAuctionEvent.InputTuple, CancelAuctionEvent.OutputTuple, CancelAuctionEvent.OutputObject>;
    

      'CreateAuction(uint256,address,address,uint256,uint256,uint256)': TypedContractEvent<CreateAuctionEvent.InputTuple, CreateAuctionEvent.OutputTuple, CreateAuctionEvent.OutputObject>;
      CreateAuction: TypedContractEvent<CreateAuctionEvent.InputTuple, CreateAuctionEvent.OutputTuple, CreateAuctionEvent.OutputObject>;
    

      'EndAuction(uint256,address,uint256)': TypedContractEvent<EndAuctionEvent.InputTuple, EndAuctionEvent.OutputTuple, EndAuctionEvent.OutputObject>;
      EndAuction: TypedContractEvent<EndAuctionEvent.InputTuple, EndAuctionEvent.OutputTuple, EndAuctionEvent.OutputObject>;
    

      'FeeCollected(uint256,uint256,uint256)': TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
      FeeCollected: TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PlaceBid(uint256,address,uint256)': TypedContractEvent<PlaceBidEvent.InputTuple, PlaceBidEvent.OutputTuple, PlaceBidEvent.OutputObject>;
      PlaceBid: TypedContractEvent<PlaceBidEvent.InputTuple, PlaceBidEvent.OutputTuple, PlaceBidEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'WithdrawPendingReturn(uint256,address,uint256)': TypedContractEvent<WithdrawPendingReturnEvent.InputTuple, WithdrawPendingReturnEvent.OutputTuple, WithdrawPendingReturnEvent.OutputObject>;
      WithdrawPendingReturn: TypedContractEvent<WithdrawPendingReturnEvent.InputTuple, WithdrawPendingReturnEvent.OutputTuple, WithdrawPendingReturnEvent.OutputObject>;
    
    };
  }