/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Auction', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Auction__factory>
getContractFactory(name: 'AuctionToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionToken__factory>
getContractFactory(name: 'AuctionV1', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionV1__factory>
getContractFactory(name: 'AuctionV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionV2__factory>
getContractFactory(name: 'MockV3Aggregator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockV3Aggregator__factory>

  getContractAt(name: 'Auction', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Auction>
getContractAt(name: 'AuctionToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionToken>
getContractAt(name: 'AuctionV1', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionV1>
getContractAt(name: 'AuctionV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionV2>
getContractAt(name: 'MockV3Aggregator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockV3Aggregator>

  deployContract(name: 'Auction', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Auction>
deployContract(name: 'AuctionToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionToken>
deployContract(name: 'AuctionV1', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionV1>
deployContract(name: 'AuctionV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionV2>
deployContract(name: 'MockV3Aggregator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockV3Aggregator>

  deployContract(name: 'Auction', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Auction>
deployContract(name: 'AuctionToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionToken>
deployContract(name: 'AuctionV1', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionV1>
deployContract(name: 'AuctionV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionV2>
deployContract(name: 'MockV3Aggregator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockV3Aggregator>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  