/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MultiSigWalletInterface extends Interface {
    getFunction(nameOrSignature: "confirm" | "confirmations" | "execute" | "isOwner" | "owners" | "required" | "submit" | "transactions"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'confirm', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmations', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'execute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owners', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'required', values?: undefined): string;
encodeFunctionData(functionFragment: 'submit', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'transactions', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'confirm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'required', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transactions', data: BytesLike): Result;
  }

  

  export interface MultiSigWallet extends BaseContract {
    
    connect(runner?: ContractRunner | null): MultiSigWallet;
    waitForDeployment(): Promise<this>;

    interface: MultiSigWalletInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    confirm: TypedContractMethod<
      [_txId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmations: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    execute: TypedContractMethod<
      [_txId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isOwner: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owners: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    required: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submit: TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _data: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    transactions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, confirmations: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'confirm'): TypedContractMethod<
      [_txId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmations'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [_txId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isOwner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'required'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submit'): TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _data: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transactions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, confirmations: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }