/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SignatureVerifierInterface extends Interface {
    getFunction(nameOrSignature: "getEthSignedMessageHash" | "getMessageHash" | "recoverSigner" | "splitSignature" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getEthSignedMessageHash', values: [string]): string;
encodeFunctionData(functionFragment: 'getMessageHash', values: [string]): string;
encodeFunctionData(functionFragment: 'recoverSigner', values: [string, BytesLike]): string;
encodeFunctionData(functionFragment: 'splitSignature', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verify', values: [string, BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getEthSignedMessageHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMessageHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'splitSignature', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface SignatureVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): SignatureVerifier;
    waitForDeployment(): Promise<this>;

    interface: SignatureVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getEthSignedMessageHash: TypedContractMethod<
      [message: string, ],
      [string],
      'view'
    >
    

    
    getMessageHash: TypedContractMethod<
      [message: string, ],
      [string],
      'view'
    >
    

    
    recoverSigner: TypedContractMethod<
      [message: string, signature: BytesLike, ],
      [string],
      'view'
    >
    

    
    splitSignature: TypedContractMethod<
      [signature: BytesLike, ],
      [[string, string, bigint] & {r: string, s: string, v: bigint }],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [message: string, signature: BytesLike, signer: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getEthSignedMessageHash'): TypedContractMethod<
      [message: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMessageHash'): TypedContractMethod<
      [message: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverSigner'): TypedContractMethod<
      [message: string, signature: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'splitSignature'): TypedContractMethod<
      [signature: BytesLike, ],
      [[string, string, bigint] & {r: string, s: string, v: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [message: string, signature: BytesLike, signer: AddressLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }