/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TimelockInterface extends Interface {
    getFunction(nameOrSignature: "GRACE_PERIOD" | "admin" | "cancelTransaction" | "changeAdmin" | "delay" | "executeTransaction" | "getBlockTimestamp" | "getTxHash" | "queueTransaction" | "queuedTransactions"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CancelTransaction" | "ExecuteTransaction" | "NewAdmin" | "QueueTransaction"): EventFragment;

    encodeFunctionData(functionFragment: 'GRACE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelTransaction', values: [AddressLike, BigNumberish, string, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'changeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'delay', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeTransaction', values: [AddressLike, BigNumberish, string, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBlockTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTxHash', values: [AddressLike, BigNumberish, string, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'queueTransaction', values: [AddressLike, BigNumberish, string, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'queuedTransactions', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'GRACE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBlockTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTxHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'queueTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'queuedTransactions', data: BytesLike): Result;
  }

  
    export namespace CancelTransactionEvent {
      export type InputTuple = [txHash: BytesLike, target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish];
      export type OutputTuple = [txHash: string, target: string, value: bigint, signature: string, data: string, executeTime: bigint];
      export interface OutputObject {txHash: string, target: string, value: bigint, signature: string, data: string, executeTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecuteTransactionEvent {
      export type InputTuple = [txHash: BytesLike, target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish];
      export type OutputTuple = [txHash: string, target: string, value: bigint, signature: string, data: string, executeTime: bigint];
      export interface OutputObject {txHash: string, target: string, value: bigint, signature: string, data: string, executeTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NewAdminEvent {
      export type InputTuple = [newAdmin: AddressLike];
      export type OutputTuple = [newAdmin: string];
      export interface OutputObject {newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QueueTransactionEvent {
      export type InputTuple = [txHash: BytesLike, target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish];
      export type OutputTuple = [txHash: string, target: string, value: bigint, signature: string, data: string, executeTime: bigint];
      export interface OutputObject {txHash: string, target: string, value: bigint, signature: string, data: string, executeTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Timelock extends BaseContract {
    
    connect(runner?: ContractRunner | null): Timelock;
    waitForDeployment(): Promise<this>;

    interface: TimelockInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    GRACE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelTransaction: TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    changeAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    delay: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    executeTransaction: TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [string],
      'payable'
    >
    

    
    getBlockTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTxHash: TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [string],
      'view'
    >
    

    
    queueTransaction: TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    queuedTransactions: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'GRACE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelTransaction'): TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'changeAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'delay'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executeTransaction'): TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'getBlockTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTxHash'): TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'queueTransaction'): TypedContractMethod<
      [target: AddressLike, value: BigNumberish, signature: string, data: BytesLike, executeTime: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'queuedTransactions'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CancelTransaction'): TypedContractEvent<CancelTransactionEvent.InputTuple, CancelTransactionEvent.OutputTuple, CancelTransactionEvent.OutputObject>;
getEvent(key: 'ExecuteTransaction'): TypedContractEvent<ExecuteTransactionEvent.InputTuple, ExecuteTransactionEvent.OutputTuple, ExecuteTransactionEvent.OutputObject>;
getEvent(key: 'NewAdmin'): TypedContractEvent<NewAdminEvent.InputTuple, NewAdminEvent.OutputTuple, NewAdminEvent.OutputObject>;
getEvent(key: 'QueueTransaction'): TypedContractEvent<QueueTransactionEvent.InputTuple, QueueTransactionEvent.OutputTuple, QueueTransactionEvent.OutputObject>;

    filters: {
      
      'CancelTransaction(bytes32,address,uint256,string,bytes,uint256)': TypedContractEvent<CancelTransactionEvent.InputTuple, CancelTransactionEvent.OutputTuple, CancelTransactionEvent.OutputObject>;
      CancelTransaction: TypedContractEvent<CancelTransactionEvent.InputTuple, CancelTransactionEvent.OutputTuple, CancelTransactionEvent.OutputObject>;
    

      'ExecuteTransaction(bytes32,address,uint256,string,bytes,uint256)': TypedContractEvent<ExecuteTransactionEvent.InputTuple, ExecuteTransactionEvent.OutputTuple, ExecuteTransactionEvent.OutputObject>;
      ExecuteTransaction: TypedContractEvent<ExecuteTransactionEvent.InputTuple, ExecuteTransactionEvent.OutputTuple, ExecuteTransactionEvent.OutputObject>;
    

      'NewAdmin(address)': TypedContractEvent<NewAdminEvent.InputTuple, NewAdminEvent.OutputTuple, NewAdminEvent.OutputObject>;
      NewAdmin: TypedContractEvent<NewAdminEvent.InputTuple, NewAdminEvent.OutputTuple, NewAdminEvent.OutputObject>;
    

      'QueueTransaction(bytes32,address,uint256,string,bytes,uint256)': TypedContractEvent<QueueTransactionEvent.InputTuple, QueueTransactionEvent.OutputTuple, QueueTransactionEvent.OutputObject>;
      QueueTransaction: TypedContractEvent<QueueTransactionEvent.InputTuple, QueueTransactionEvent.OutputTuple, QueueTransactionEvent.OutputObject>;
    
    };
  }