/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxy from './proxy/index.js';
export * as test from './test/index.js';
export { Auction__factory } from './Auction__factory.js';
export { AuctionToken__factory } from './AuctionToken__factory.js';
export { AuctionV1__factory } from './AuctionV1__factory.js';
export { AuctionV2__factory } from './AuctionV2__factory.js';