/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuctionProxyAdmin } from './AuctionProxyAdmin.js';
export type { AuctionTransparentProxy } from './AuctionTransparentProxy.js';