/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuctionProxyAdmin__factory } from './AuctionProxyAdmin__factory.js';
export { AuctionTransparentProxy__factory } from './AuctionTransparentProxy__factory.js';